# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pydoc_quarto',
                'doc_host': 'https://hamelsmu.github.io',
                'git_url': 'https://github.com/hamelsmu/pydoc_quarto',
                'lib_path': 'pydoc_quarto'},
  'syms': { 'pydoc_quarto.core': { 'pydoc_quarto.core.gen_md': ('core.html#gen_md', 'pydoc_quarto/core.py'),
                                   'pydoc_quarto.core.get_modules': ('core.html#get_modules', 'pydoc_quarto/core.py'),
                                   'pydoc_quarto.core.gethelp': ('core.html#gethelp', 'pydoc_quarto/core.py'),
                                   'pydoc_quarto.core.help2md': ('core.html#help2md', 'pydoc_quarto/core.py')}}}
