---
title: "docments"
description: "module fastcore.docments in fastcore"
---

## Classes

    builtins.object
        inspect._empty
    
    
### empty
    
<strong>empty = class _empty(builtins.object)</strong>
    
     |  Marker object for Signature.empty and Parameter.empty.
     |  
     |  Data descriptors defined here:
     |  
     |  __dict__
     |      dictionary for instance variables (if defined)
     |  
     |  __weakref__
     |      list of weak references to the object (if defined)

## Functions

    
### `docments`
    
<strong>docments(elt, full=False, *, returns=True, eval_str=False)</strong>
    
        Generates a `docment`
    
### `docstring`
    
<strong>docstring(sym)</strong>
    
        Get docstring for `sym` for functions ad classes
    
### `get_dataclass_source`
    
<strong>get_dataclass_source(s)</strong>
    
        Get source code for dataclass `s`
    
### `get_name`
    
<strong>get_name(obj)</strong>
    
        Get the name of `obj`
    
### `get_source`
    
<strong>get_source(s)</strong>
    
        Get source code for string, function object or dataclass `s`
    
### `isdataclass`
    
<strong>isdataclass(s)</strong>
    
        Check if `s` is a dataclass but not a dataclass' instance
    
### `parse_docstring`
    
<strong>parse_docstring(sym)</strong>
    
        Parse a numpy-style docstring in `sym`
    
### `qual_name`
    
<strong>qual_name(obj)</strong>
    
        Get the qualified name of `obj`

