---
title: "xtras"
description: "module fastcore.xtras in fastcore"
---

## Classes

    builtins.object
        EventTimer
        IterLen
            ReindexCollection(fastcore.basics.GetAttr, IterLen)
    fastcore.basics.GetAttr(builtins.object)
        ContextManagers
        ReindexCollection(fastcore.basics.GetAttr, IterLen)
    string.Formatter(builtins.object)
        PartialFormatter
    
    
### ContextManagers
    


```{=html}
<blockquote><strong><code>class ContextManagers(fastcore.basics.GetAttr)</code></strong></blockquote>
```


    
     |  ContextManagers(mgrs)
     |  
     |  Wrapper for `contextlib.ExitStack` which enters a collection of context managers
     |  
     |  Method resolution order:
     |      ContextManagers
     |      fastcore.basics.GetAttr
     |      builtins.object
     |  
     |  Methods defined here:
     |  
     |  
#### `ContextManagers.__enter__`
     |  
     |  __enter__(self)
     |  
     |  
#### `ContextManagers.__exit__`
     |  
     |  __exit__(self, *args, **kwargs)
     |  
     |  
#### `ContextManagers.__init__`
     |  
     |  __init__(self, mgrs)
     |      Initialize self.  See help(type(self)) for accurate signature.
     |  
     |  ----------------------------------------------------------------------
     |  Methods inherited from fastcore.basics.GetAttr:
     |  
     |  
#### `GetAttr.__dir__`
     |  
     |  __dir__(self)
     |      Default dir() implementation.
     |  
     |  
#### `GetAttr.__getattr__`
     |  
     |  __getattr__(self, k)
     |  
     |  
#### `GetAttr.__setstate__`
     |  
     |  __setstate__(self, data)
     |  
     |  ----------------------------------------------------------------------
     |  Data descriptors inherited from fastcore.basics.GetAttr:
     |  
     |  __dict__
     |      dictionary for instance variables (if defined)
     |  
     |  __weakref__
     |      list of weak references to the object (if defined)
    
### EventTimer
    


```{=html}
<blockquote><strong><code>class EventTimer(builtins.object)</code></strong></blockquote>
```


    
     |  EventTimer(store=5, span=60)
     |  
     |  An event timer with history of `store` items of time `span`
     |  
     |  Methods defined here:
     |  
     |  
#### `EventTimer.__init__`
     |  
     |  __init__(self, store=5, span=60)
     |      Initialize self.  See help(type(self)) for accurate signature.
     |  
     |  
#### `EventTimer.add`
     |  
     |  add(self, n=1)
     |      Record `n` events
     |  
     |  ----------------------------------------------------------------------
     |  Readonly properties defined here:
     |  
     |  duration
     |  
     |  freq
     |  
     |  ----------------------------------------------------------------------
     |  Data descriptors defined here:
     |  
     |  __dict__
     |      dictionary for instance variables (if defined)
     |  
     |  __weakref__
     |      list of weak references to the object (if defined)
    
### IterLen
    


```{=html}
<blockquote><strong><code>class IterLen(builtins.object)</code></strong></blockquote>
```


    
     |  Base class to add iteration to anything supporting `__len__` and `__getitem__`
     |  
     |  Methods defined here:
     |  
     |  
#### `IterLen.__iter__`
     |  
     |  __iter__(self)
     |  
     |  ----------------------------------------------------------------------
     |  Data descriptors defined here:
     |  
     |  __dict__
     |      dictionary for instance variables (if defined)
     |  
     |  __weakref__
     |      list of weak references to the object (if defined)
    
### PartialFormatter
    


```{=html}
<blockquote><strong><code>class PartialFormatter(string.Formatter)</code></strong></blockquote>
```


    
     |  A `string.Formatter` that doesn't error on missing fields, and tracks missing fields and unused args
     |  
     |  Method resolution order:
     |      PartialFormatter
     |      string.Formatter
     |      builtins.object
     |  
     |  Methods defined here:
     |  
     |  
#### `PartialFormatter.__init__`
     |  
     |  __init__(self)
     |      Initialize self.  See help(type(self)) for accurate signature.
     |  
     |  
#### `PartialFormatter.check_unused_args`
     |  
     |  check_unused_args(self, used, args, kwargs)
     |  
     |  
#### `PartialFormatter.get_field`
     |  
     |  get_field(self, nm, args, kwargs)
     |  
     |  ----------------------------------------------------------------------
     |  Methods inherited from string.Formatter:
     |  
     |  
#### `Formatter.convert_field`
     |  
     |  convert_field(self, value, conversion)
     |  
     |  
#### `Formatter.format`
     |  
     |  format(self, format_string, /, *args, **kwargs)
     |  
     |  
#### `Formatter.format_field`
     |  
     |  format_field(self, value, format_spec)
     |  
     |  
#### `Formatter.get_value`
     |  
     |  get_value(self, key, args, kwargs)
     |  
     |  
#### `Formatter.parse`
     |  
     |  parse(self, format_string)
     |      # returns an iterable that contains tuples of the form:
     |      # (literal_text, field_name, format_spec, conversion)
     |      # literal_text can be zero length
     |      # field_name can be None, in which case there's no
     |      #  object to format and output
     |      # if field_name is not None, it is looked up, formatted
     |      #  with format_spec and conversion and then used
     |  
     |  
#### `Formatter.vformat`
     |  
     |  vformat(self, format_string, args, kwargs)
     |  
     |  ----------------------------------------------------------------------
     |  Data descriptors inherited from string.Formatter:
     |  
     |  __dict__
     |      dictionary for instance variables (if defined)
     |  
     |  __weakref__
     |      list of weak references to the object (if defined)
    
### ReindexCollection
    


```{=html}
<blockquote><strong><code>class ReindexCollection(fastcore.basics.GetAttr, IterLen)</code></strong></blockquote>
```


    
     |  ReindexCollection(coll, idxs=None, cache=None, tfm=<function noop at 0x103bc1480>)
     |  
     |  Reindexes collection `coll` with indices `idxs` and optional LRU cache of size `cache`
     |  
     |  Method resolution order:
     |      ReindexCollection
     |      fastcore.basics.GetAttr
     |      IterLen
     |      builtins.object
     |  
     |  Methods defined here:
     |  
     |  
#### `ReindexCollection.__getitem__`
     |  
     |  __getitem__(self, i)
     |  
     |  
#### `ReindexCollection.__getstate__`
     |  
     |  __getstate__(self)
     |  
     |  
#### `ReindexCollection.__init__`
     |  
     |  __init__(self, coll, idxs=None, cache=None, tfm=<function noop at 0x103bc1480>)
     |      Initialize self.  See help(type(self)) for accurate signature.
     |  
     |  
#### `ReindexCollection.__len__`
     |  
     |  __len__(self)
     |  
     |  
#### `ReindexCollection.__setstate__`
     |  
     |  __setstate__(self, s)
     |  
     |  
#### `ReindexCollection.cache_clear`
     |  
     |  cache_clear(self)
     |      Clear LRU cache
     |  
     |  
#### `ReindexCollection.reindex`
     |  
     |  reindex(self, idxs)
     |      Replace `self.idxs` with idxs
     |  
     |  
#### `ReindexCollection.shuffle`
     |  
     |  shuffle(self)
     |      Randomly shuffle indices
     |  
     |  ----------------------------------------------------------------------
     |  Methods inherited from fastcore.basics.GetAttr:
     |  
     |  
#### `GetAttr.__dir__`
     |  
     |  __dir__(self)
     |      Default dir() implementation.
     |  
     |  
#### `GetAttr.__getattr__`
     |  
     |  __getattr__(self, k)
     |  
     |  ----------------------------------------------------------------------
     |  Data descriptors inherited from fastcore.basics.GetAttr:
     |  
     |  __dict__
     |      dictionary for instance variables (if defined)
     |  
     |  __weakref__
     |      list of weak references to the object (if defined)
     |  
     |  ----------------------------------------------------------------------
     |  Methods inherited from IterLen:
     |  
     |  
#### `IterLen.__iter__`
     |  
     |  __iter__(self)

## Functions

    
### `autostart`
    


```{=html}
<blockquote><strong><code>autostart(g)</code></strong></blockquote>
```


    
        Decorator that automatically starts a generator
    
### `bunzip`
    


```{=html}
<blockquote><strong><code>bunzip(fn)</code></strong></blockquote>
```


    
        bunzip `fn`, raising exception if output already exists
    
### `console_help`
    


```{=html}
<blockquote><strong><code>console_help(libname: 'str')</code></strong></blockquote>
```


    
        Show help for all console scripts from `libname`
    
### `dict2obj`
    


```{=html}
<blockquote><strong><code>dict2obj(d, list_func=<class 'fastcore.foundation.L'>, dict_func=<class 'fastcore.basics.AttrDict'>)</code></strong></blockquote>
```


    
        Convert (possibly nested) dicts (or lists of dicts) to `AttrDict`
    
### `dumps`
    


```{=html}
<blockquote><strong><code>dumps(obj, **kw)</code></strong></blockquote>
```


    
        Same as `json.dumps`, but uses `ujson` if available
    
### `get_source_link`
    


```{=html}
<blockquote><strong><code>get_source_link(func)</code></strong></blockquote>
```


    
        Return link to `func` in source code
    
### `globtastic`
    


```{=html}
<blockquote><strong><code>globtastic(path: 'Path | str', recursive: 'bool' = True, symlinks: 'bool' = True, file_glob: 'str' = None, file_re: 'str' = None, folder_re: 'str' = None, skip_file_glob: 'str' = None, skip_file_re: 'str' = None, skip_folder_re: 'str' = None, func: 'callable' = <function join at 0x1034eeb90>, ret_folders: 'bool' = False) -> 'L'</code></strong></blockquote>
```


    
        A more powerful `glob`, including regex matches, symlink handling, and skip parameters
    
### `image_size`
    


```{=html}
<blockquote><strong><code>image_size(fn)</code></strong></blockquote>
```


    
        Tuple of (w,h) for png, gif, or jpg; `None` otherwise
    
### `is_listy`
    


```{=html}
<blockquote><strong><code>is_listy(x)</code></strong></blockquote>
```


    
        `isinstance(x, (tuple,list,L,slice,Generator))`
    
### `join_path_file`
    


```{=html}
<blockquote><strong><code>join_path_file(file, path, ext='')</code></strong></blockquote>
```


    
        Return `path/file` if file is a string or a `Path`, file otherwise
    
### `load_pickle`
    


```{=html}
<blockquote><strong><code>load_pickle(fn)</code></strong></blockquote>
```


    
        Load a pickle file from a file name or opened file
    
### `loads`
    


```{=html}
<blockquote><strong><code>loads(s, **kw)</code></strong></blockquote>
```


    
        Same as `json.loads`, but handles `None`
    
### `loads_multi`
    


```{=html}
<blockquote><strong><code>loads_multi(s: 'str')</code></strong></blockquote>
```


    
        Generator of >=0 decoded json dicts, possibly with non-json ignored text at start and end
    
### `local2utc`
    


```{=html}
<blockquote><strong><code>local2utc(dt: 'datetime') -> 'datetime'</code></strong></blockquote>
```


    
        Convert `dt` from local to UTC time
    
### `mapped`
    


```{=html}
<blockquote><strong><code>mapped(f, it)</code></strong></blockquote>
```


    
        map `f` over `it`, unless it's not listy, in which case return `f(it)`
    
### `maybe_open`
    


```{=html}
<blockquote><strong><code>maybe_open(f, mode='r', **kwargs)</code></strong></blockquote>
```


    
        Context manager: open `f` if it is a path (and close on exit)
    
### `mkdir`
    


```{=html}
<blockquote><strong><code>mkdir(path, exist_ok=False, parents=False, overwrite=False, **kwargs)</code></strong></blockquote>
```


    
        Creates and returns a directory defined by `path`, optionally removing previous existing directory if `overwrite` is `True`
    
### `modified_env`
    


```{=html}
<blockquote><strong><code>modified_env(*delete, **replace)</code></strong></blockquote>
```


    
        Context manager temporarily modifying `os.environ` by deleting `delete` and replacing `replace`
    
### `modify_exception`
    


```{=html}
<blockquote><strong><code>modify_exception(e: 'Exception', msg: 'str' = None, replace: 'bool' = False) -> 'Exception'</code></strong></blockquote>
```


    
        Modifies `e` with a custom message attached
    
### `obj2dict`
    


```{=html}
<blockquote><strong><code>obj2dict(d)</code></strong></blockquote>
```


    
        Convert (possibly nested) AttrDicts (or lists of AttrDicts) to `dict`
    
### `open_file`
    


```{=html}
<blockquote><strong><code>open_file(fn, mode='r', **kwargs)</code></strong></blockquote>
```


    
        Open a file, with optional compression if gz or bz2 suffix
    
### `partial_format`
    


```{=html}
<blockquote><strong><code>partial_format(s: 'str', **kwargs)</code></strong></blockquote>
```


    
        string format `s`, ignoring missing field errors, returning missing and extra fields
    
### `repo_details`
    


```{=html}
<blockquote><strong><code>repo_details(url)</code></strong></blockquote>
```


    
        Tuple of `owner,name` from ssh or https git repo `url`
    
### `repr_dict`
    


```{=html}
<blockquote><strong><code>repr_dict(d)</code></strong></blockquote>
```


    
        Print nested dicts and lists, such as returned by `dict2obj`
    
### `round_multiple`
    


```{=html}
<blockquote><strong><code>round_multiple(x, mult, round_down=False)</code></strong></blockquote>
```


    
        Round `x` to nearest multiple of `mult`
    
### `run`
    


```{=html}
<blockquote><strong><code>run(cmd, *rest, same_in_win=False, ignore_ex=False, as_bytes=False, stderr=False)</code></strong></blockquote>
```


    
        Pass `cmd` (splitting with `shlex` if string) to `subprocess.run`; return `stdout`; raise `IOError` if fails
    
### `save_pickle`
    


```{=html}
<blockquote><strong><code>save_pickle(fn, o)</code></strong></blockquote>
```


    
        Save a pickle file, to a file name or opened file
    
### `set_num_threads`
    


```{=html}
<blockquote><strong><code>set_num_threads(nt)</code></strong></blockquote>
```


    
        Get numpy (and others) to use `nt` threads
    
### `shufflish`
    


```{=html}
<blockquote><strong><code>shufflish(x, pct=0.04)</code></strong></blockquote>
```


    
        Randomly relocate items of `x` up to `pct` of `len(x)` from their starting location
    
### `sparkline`
    


```{=html}
<blockquote><strong><code>sparkline(data, mn=None, mx=None, empty_zero=False)</code></strong></blockquote>
```


    
        Sparkline for `data`, with `None`s (and zero, if `empty_zero`) shown as empty column
    
### `stringfmt_names`
    


```{=html}
<blockquote><strong><code>stringfmt_names(s: 'str') -> 'list'</code></strong></blockquote>
```


    
        Unique brace-delimited names in `s`
    
### `trace`
    


```{=html}
<blockquote><strong><code>trace(f)</code></strong></blockquote>
```


    
        Add `set_trace` to an existing function `f`
    
### `truncstr`
    


```{=html}
<blockquote><strong><code>truncstr(s: 'str', maxlen: 'int', suf: 'str' = '…', space='') -> 'str'</code></strong></blockquote>
```


    
        Truncate `s` to length `maxlen`, adding suffix `suf` if truncated
    
### `untar_dir`
    


```{=html}
<blockquote><strong><code>untar_dir(fname, dest, rename=False, overwrite=False)</code></strong></blockquote>
```


    
        untar `file` into `dest`, creating a directory if the root contains more than one item
    
### `utc2local`
    


```{=html}
<blockquote><strong><code>utc2local(dt: 'datetime') -> 'datetime'</code></strong></blockquote>
```


    
        Convert `dt` from UTC to local time
    
### `walk`
    


```{=html}
<blockquote><strong><code>walk(path: 'Path | str', symlinks: 'bool' = True, keep_file: 'callable' = <function ret_true at 0x103c148b0>, keep_folder: 'callable' = <function ret_true at 0x103c148b0>, skip_folder: 'callable' = <function ret_false at 0x103c14940>, func: 'callable' = <function join at 0x1034eeb90>, ret_folders: 'bool' = False)</code></strong></blockquote>
```


    
        Generator version of `os.walk`, using functions to filter files and folders

